---

installed_packages:
  - ack
  - base-devel
  - clang
  - cmake
  - cronie
  - curl
  - git
  - htop
  - ltrace
  - ntp
  - openbsd-netcat
  - python
  - python-pip
  - python-virtualenv
  - python-virtualenvwrapper
  - python2
  - python2-pip
  - rsync
  - strace
  - svn
  - the_silver_searcher
  - tmux
  - valgrind
  - vim
  - wget
  - zsh

# NOTE: delete packages by moving them to the list below!

# Order may matter for dependencies
removed_packages: []

# Systemd services
systemd_services:
  - name: cronie
    state: started
    enabled: yes
  - name: ntpd
    state: started
    enabled: yes
  - name: avahi-daemon
    state: stopped
    enabled: yes
